export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_ROBOTS_PEDING ="REQUEST_ROBOTS_PEDING";
export const REQUEST_ROBOTS_SUCCESS ="REQUEST_ROBOTS_SUCCESS";
export const REQUEST_ROBOTS_FAILD ="REQUEST_ROBOTS_FAILD";